### ISSUE TITLE
Impossible to yarn start Examples

### ISSUE THREAD

**Issue by hotgeart** [software-mansion/react-native-gesture-handler#1196]
## Description

Impossible to start the Examples app. Highly possible it's coming from expo, but I don't have any problem with my others apps. Old or newly created.

### Screenshots

[https://i.imgur.com/RjP7LLO.png](https://i.imgur.com/RjP7LLO.png)

## Steps To Reproduce

I followed the instructions: https://docs.swmansion.com/react-native-gesture-handler/docs/example

1. git clone https://github.com/software-mansion/react-native-gesture-handler.git
2. cd react-native-gesture-handler
3. yarn
4. cd Example
5. yarn
6. yarn start

### Expected behavior

Start the app

### Actual behavior

Error in console:

```
error Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class. Run CLI with --verbose flag for more details.
SyntaxError: Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class
    at new RegExp (<anonymous>)
    at blacklist (C:\Users\hotge\Desktop\react-native\react-native-gesture-handler\Example\node_modules\react-native\node_modules\metro-config\src\defaults\blacklist.js:34:10)
    at getBlacklistRE (C:\Users\hotge\Desktop\react-native\react-native-gesture-handler\Example\node_modules\react-native\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:69:59)
    at getDefaultConfig (C:\Users\hotge\Desktop\react-native\react-native-gesture-handler\Example\node_modules\react-native\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:85:20)
    at load (C:\Users\hotge\Desktop\react-native\react-native-gesture-handler\Example\node_modules\react-native\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:121:25)
    at Object.runServer [as func] (C:\Users\hotge\Desktop\react-native\react-native-gesture-handler\Example\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\server\runServer.js:82:58)
    at Command.handleAction (C:\Users\hotge\Desktop\react-native\react-native-gesture-handler\Example\node_modules\react-native\node_modules\@react-native-community\cli\build\cliEntry.js:160:21)
    at Command.listener (C:\Users\hotge\Desktop\react-native\react-native-gesture-handler\Example\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:315:20)
    at Command.parseArgs (C:\Users\hotge\Desktop\react-native\react-native-gesture-handler\Example\node_modules\commander\index.js:651:12)
error Command failed with exit code 1.
```

## Snack or minimal code example

n/a

## Package versions

n/a

**Comment by jakub-gonet** [comment]
This is related to the metro and not RNGH.

Try applying the fix from this issue https://github.com/facebook/metro/issues/578 and please report back if it made it work.

Closing for now.

**Comment by hotgeart** [comment]
The correct file in my case was : `\react-native-gesture-handler\Example\node_modules\react-native\node_modules\metro-config\src\defaults\blacklist.js`

**Comment by lexguy** [comment]
> The correct file in my case was : `\react-native-gesture-handler\Example\node_modules\react-native\node_modules\metro-config\src\defaults\blacklist.js`
it does not work.. do you have other operations?
