### ISSUE TITLE
[Android] Crash when upgrading from 1.6.1 to 1.7.0 or 1.8.0.

### ISSUE THREAD

**Issue by curiousdustin** [software-mansion/react-native-gesture-handler#1204]
## Description

When I upgrade `react-native-gesture-handler` from 1.6.1 to either 1.7.0 or 1.8.0, my application crashes on launch with the following error on Android:

```
2020-09-30 15:18:44.112 29749-29749/my.appname.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: my.appname.app, PID: 29749
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{my.appname.app/my.appname.app.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "my.appname.app.MainActivity" on path: DexPathList[[zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/android.test.runner.jar", zip file "/data/app/my.appname.app-w1pEkEI82d8M651urhOltQ==/base.apk"],nativeLibraryDirectories=[/data/app/my.appname.app-w1pEkEI82d8M651urhOltQ==/lib/arm64, /data/app/my.appname.app-w1pEkEI82d8M651urhOltQ==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2998)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3229)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6981)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "my.appname.app.MainActivity" on path: DexPathList[[zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/android.test.runner.jar", zip file "/data/app/my.appname.app-w1pEkEI82d8M651urhOltQ==/base.apk"],nativeLibraryDirectories=[/data/app/my.appname.app-w1pEkEI82d8M651urhOltQ==/lib/arm64, /data/app/my.appname.app-w1pEkEI82d8M651urhOltQ==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1215)

```

### Expected behavior

No crash, as in 1.6.1.

### Actual behavior

App crashes.

## Package versions

- React: 16.13.1
- React Native: 0.63.3
- React Native Gesture Handler: 1.7.0 or 1.8.0

**Comment by jakub-gonet** [comment]
Run gradlew clean inside android/ and check if it fixes this problem. This is more likely cache issue.

Closing until more info is given.

**Comment by curiousdustin** [comment]
@jakub-gonet, thank you for pointing this out. That seems to have been my issue. Sorry for the false alarm.
