### ISSUE TITLE
NPE, 'android.widget.EdgeEffect.onRelease()' on a null object reference

### ISSUE THREAD

**Issue by thanakij** [software-mansion/react-native-gesture-handler#1644]
## Description

We found a new NullPointerException (NPE) crash and report it here.

### Screenshots

Please see the screenshot below.

![screenshot](https://i.imgur.com/APV4zwV.png)

## Steps To Reproduce

N/A. I am aware of this issue from Crashlytics.

## Snack or minimal code example

I cannot reproduce this but below is the log.

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.EdgeEffect.onRelease()' on a null object reference
       at android.widget.ScrollView.endDrag(ScrollView.java:1719)
       at android.widget.ScrollView.onTouchEvent(ScrollView.java:782)
       at com.facebook.react.views.scroll.ReactScrollView.onTouchEvent(ReactScrollView.java:299)
       at android.view.View.dispatchTouchEvent(View.java:11916)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2982)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2656)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2670)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2670)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2670)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2670)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2670)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2670)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2670)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2670)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2670)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2670)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2670)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2670)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2670)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2670)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2670)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2670)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2670)
       at com.swmansion.gesturehandler.react.RNGestureHandlerRootView.dispatchTouchEvent(RNGestureHandlerRootView.java:66)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2670)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2670)
       at com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView.dispatchTouchEvent(RNGestureHandlerEnabledRootView.java:39)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2670)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2670)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2670)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2670)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2670)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:530)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1879)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3503)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:480)
       at android.view.View.dispatchPointerEvent(View.java:12155)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5372)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5118)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4595)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4655)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4614)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4767)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4622)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4824)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4595)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4655)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4614)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4622)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4595)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7300)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7274)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7235)
       at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4341)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:198)
       at android.app.ActivityThread.main(ActivityThread.java:7055)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:836)
```

## Package versions

- React: 16.11.0
- React Native: 0.62.3
- React Native Gesture Handler: 1.10.3

**Comment by piaskowyk** [comment]
Hey, could you provide a repo to reproduce your issue?
