### ISSUE TITLE
bug: FATAL EXCEPTION: mqt_native_modules

### ISSUE THREAD

**Issue by thereis** [software-mansion/react-native-gesture-handler#1724]
## Description
Currently the app is throwing an error after reloading the app from a code-push update.

### Screenshots
None.

## Steps To Reproduce

1. Update the app code push bundle
2. Face the error

### Expected behavior
Not crash

### Actual behavior
Crashing

## Snack or minimal code example
```
--------- beginning of crash
11-16 17:18:32.047  3736  3850 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
11-16 17:18:32.047  3736  3850 E AndroidRuntime: Process: ev.sandbox, PID: 3736
11-16 17:18:32.047  3736  3850 E AndroidRuntime: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Could find root view for a given ancestor with tag 5483
11-16 17:18:32.047  3736  3850 E AndroidRuntime: 	at com.swmansion.gesturehandler.react.RNGestureHandlerModule.tryInitializeHandlerForReactRootView(RNGestureHandlerModule.java:577)
11-16 17:18:32.047  3736  3850 E AndroidRuntime: 	at com.swmansion.gesturehandler.react.RNGestureHandlerModule.attachGestureHandler(RNGestureHandlerModule.java:487)
11-16 17:18:32.047  3736  3850 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-16 17:18:32.047  3736  3850 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
11-16 17:18:32.047  3736  3850 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
11-16 17:18:32.047  3736  3850 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
11-16 17:18:32.047  3736  3850 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
11-16 17:18:32.047  3736  3850 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-16 17:18:32.047  3736  3850 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
11-16 17:18:32.047  3736  3850 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:246)
11-16 17:18:32.047  3736  3850 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
11-16 17:18:32.047  3736  3850 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
```

## Package versions

- React: 17.0.2
- React Native: 0.66.2
- React Native Gesture Handler: ^1.10.3

**Comment by federicot** [comment]
related #1675

**Comment by kkafar** [comment]
Hi @thereis
It seems that your problem should be resolved with [this PR](https://github.com/software-mansion/react-native-gesture-handler/pull/1936). Can you confirm this works for you now?

**Comment by thereis** [comment]
@kkafar I will test it today and I will let you know about it! Thanks for replying the ticket!

**Comment by FadiAboMsalam** [comment]
I have same issue with latest  "react-native-gesture-handler": "^2.3.2" and latest "react-native-code-push": "^7.0.4",

any suggestions on this ?

**Comment by j-piasecki** [comment]
@FadiAboMsalam Could you try upgrading to Gesture Handler 2.4?
