### ISSUE TITLE
Invariant Violation: "RNGestureHandlerRootView" 

### ISSUE THREAD

**Issue by GeeteshSingh** [software-mansion/react-native-gesture-handler#1915]
I am making a basic news app with fetching API. It is working in IOS simulator but it’s not working in android. Currently I am using expo V5.2.0
and the error is:
This error is located at:
    in RNGestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by StackView)
    in StackView (created by StackNavigator)
    in Unknown (created by StackNavigator)
    in StackNavigator (created by RootStack)
    in RootStack (created by App)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by App)
    in App (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0

Invariant Violation: requireNativeComponent: "RNGestureHandlerRootView" was not found in the UIManager. I don’t know why this is happening but I want to make my App work on cross platforms.
### Platforms

- [Yes] iOS
- [Yes] Android
- [No] Web

### Screenshots
1) on Iphone 13:
<img width="304" alt="image" src="https://user-images.githubusercontent.com/14001562/156831591-b1cfe13d-1707-4f0e-a346-6e915e9dca95.png">
2) On expo go app on android:
<img width="756" alt="image" src="https://user-images.githubusercontent.com/14001562/156831789-c0dbeb2a-2419-4b93-95f7-e3bbcde7d15e.png">

## Steps To Reproduce

1. No steps just following documentation and some react native frameworks

### Actual behavior
Working on iPhone but not in android.
## Snack or minimal code example
 https://github.com/GeeteshSingh/LawLive

## Package versions

- React:     "react": "17.0.1",
- React Native:     "react-native": "0.64.3",
- React Native Gesture Handler:     "react-native-gesture-handler": "^2.3.0",
- React Native Reanimated:     "react-native-reanimated": "^2.4.1",

**Comment by GeeteshSingh** [comment]
deleted node_modules then used expo install. The issue was due to the expo version not supporting new react-navigation and native versions.
