### ISSUE TITLE
:app:mergeLibDexDebug FAILURE new Architecure rn v0.69.7

### ISSUE THREAD

**Issue by LucaDotti** [software-mansion/react-native-gesture-handler#2345]
### Description

Hello, I'm facing some difficulties in building my project with the new architecture enabled and it looks like the issue comes from react-native-gesture-handler. 
A bit of backgroun, my project started as an expo project and I then ejected and all works fine. After discovering the new architecture, I wanted to give it a try, however, I was still using expo. So, I started to remove all expo dependencies and I was successfully able to start the project in "plain react native".
I then tried to enable the new architecture and after some failures due to cmake, ndk etc... I get this :app:mergeLibDexDebug FAILED duplicate_classes error. Note that from the error logs, you will see that it is conflicting with the react-native-svg dependency, however, after removing  this dependencies, I have similar error (on another class) with is conflicting with react-native dependecy. I suspect that the issue is not given by other dependencies, other than react-native-gesture-handler.
Unfortunately, Im afraid that I cannot share a reproducible repository as it would be hard to remove company code, but if the issue cannot be solved without a repro repo, I will try to create one.

Thank you in advance!

**What I tried**:

- Use different versions of react-native-gesture-handler
- Remove completely the node_modules and `yarn`
- Clean with `./gradlew clean`

**What I did not tried**:

- Migrate to react native v0.70+

**Here is the output of the build**:

```
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
(node:76712) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Jetifier found 1766 file(s) to forward-jetify. Using 12 workers...
info JS server already running.
info Detected architectures x86
info Installing the app...

...

> Configure project :react-native-gesture-handler
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [24.0.8215888] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
...
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [24.0.8215888] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir

> Configure project :react-native-reanimated
No AAR for react-native-reanimated found. Attempting to build from source.
Android gradle plugin: 7.1.1
Gradle: 7.3.3
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.
...
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [24.0.8215888] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir

...


> Task :react-native-gesture-handler:generateCodegenSchemaFromJavaScript
Execution optimizations have been disabled for task ':react-native-gesture-handler:generateCodegenSchemaFromJavaScript' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/luca/Documents/wymy/v1.1.55/wymy-native-test-3/wymy-native-new-2/wymy-no-expo-splashscreen'. Reason: Task ':react-native-gesture-handler:generateCodegenSchemaFromJavaScript' uses this output of task ':ReactAndroid:buildCMakeDebug[x86][fabricjni,hermes-executor-debug,etc]' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.


> Task :app:mergeLibDexDebug FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.
423 actionable tasks: 18 executed, 405 up-to-date
CMake Deprecation Warning at CMakeLists.txt:42 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


ERROR:/Users/luca/Documents/wymy/v1.1.55/wymy-native-test-3/wymy-native-new-2/wymy-no-expo-splashscreen/node_modules/react-native-gesture-handler/android/build/.transforms/a7b112a41403fb3e84d4a98f97e0f1c6/transformed/classes/classes.dex: D8: Type com.facebook.react.viewmanagers.RNSVGCircleManagerDelegate is defined multiple times: /Users/luca/Documents/wymy/v1.1.55/wymy-native-test-3/wymy-native-new-2/wymy-no-expo-splashscreen/node_modules/react-native-gesture-handler/android/build/.transforms/a7b112a41403fb3e84d4a98f97e0f1c6/transformed/classes/classes.dex, /Users/luca/Documents/wymy/v1.1.55/wymy-native-test-3/wymy-native-new-2/wymy-no-expo-splashscreen/node_modules/react-native-svg/android/build/.transforms/8ab24842468869e5816593076e7e99ca/transformed/classes/classes.dex
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Type com.facebook.react.viewmanagers.RNSVGCircleManagerDelegate is defined multiple times: /Users/luca/Documents/wymy/v1.1.55/wymy-native-test-3/wymy-native-new-2/wymy-no-expo-splashscreen/node_modules/react-native-gesture-handler/android/build/.transforms/a7b112a41403fb3e84d4a98f97e0f1c6/transformed/classes/classes.dex, /Users/luca/Documents/wymy/v1.1.55/wymy-native-test-3/wymy-native-new-2/wymy-no-expo-splashscreen/node_modules/react-native-svg/android/build/.transforms/8ab24842468869e5816593076e7e99ca/transformed/classes/classes.dex
	at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:151)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:138)
	at com.android.build.gradle.internal.tasks.DexMergingWorkAction.merge(DexMergingTask.kt:859)
	at com.android.build.gradle.internal.tasks.DexMergingWorkAction.run(DexMergingTask.kt:805)
	at com.android.build.gradle.internal.profile.ProfileAwareWorkAction.execute(ProfileAwareWorkAction.kt:74)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:66)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:62)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:62)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:59)
	at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:206)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:214)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: /Users/luca/Documents/wymy/v1.1.55/wymy-native-test-3/wymy-native-new-2/wymy-no-expo-splashscreen/node_modules/react-native-gesture-handler/android/build/.transforms/a7b112a41403fb3e84d4a98f97e0f1c6/transformed/classes/classes.dex
	at Version.fakeStackEntry(Version_3.1.51.java:0)
	at com.android.tools.r8.internal.oO0.a(SourceFile:68)
	at com.android.tools.r8.internal.oO0.a(SourceFile:28)
	at com.android.tools.r8.internal.oO0.a(SourceFile:27)
	at com.android.tools.r8.internal.oO0.b(SourceFile:3)
	at com.android.tools.r8.D8.run(D8.java:11)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:136)
	... 33 more
Caused by: com.android.tools.r8.internal.b: Type com.facebook.react.viewmanagers.RNSVGCircleManagerDelegate is defined multiple times: /Users/luca/Documents/wymy/v1.1.55/wymy-native-test-3/wymy-native-new-2/wymy-no-expo-splashscreen/node_modules/react-native-gesture-handler/android/build/.transforms/a7b112a41403fb3e84d4a98f97e0f1c6/transformed/classes/classes.dex, /Users/luca/Documents/wymy/v1.1.55/wymy-native-test-3/wymy-native-new-2/wymy-no-expo-splashscreen/node_modules/react-native-svg/android/build/.transforms/8ab24842468869e5816593076e7e99ca/transformed/classes/classes.dex
	at com.android.tools.r8.internal.il1.a(SourceFile:14)
	at com.android.tools.r8.internal.il1.a(SourceFile:22)
	at com.android.tools.r8.internal.lf1.b(SourceFile:6)
	at com.android.tools.r8.internal.lf1.a(SourceFile:23)
	at com.android.tools.r8.internal.lf1.a(SourceFile:10)
	at java.base/java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:2048)
	at com.android.tools.r8.internal.lf1.a(SourceFile:6)
	at com.android.tools.r8.graph.r2$a.f(SourceFile:4)
	at com.android.tools.r8.dex.b.a(SourceFile:96)
	at com.android.tools.r8.dex.b.a(SourceFile:21)
	at com.android.tools.r8.D8.a(D8.java:21)
	at com.android.tools.r8.D8.d(D8.java:11)
	at com.android.tools.r8.D8.b(D8.java:1)
	at com.android.tools.r8.internal.oO0.a(SourceFile:24)
	... 36 more


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeLibDexDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingTaskDelegate
   > There was a failure while executing work items
      > A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingWorkAction
         > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
           Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
           Type com.facebook.react.viewmanagers.RNSVGCircleManagerDelegate is defined multiple times: /Users/luca/Documents/wymy/v1.1.55/wymy-native-test-3/wymy-native-new-2/wymy-no-expo-splashscreen/node_modules/react-native-gesture-handler/android/build/.transforms/a7b112a41403fb3e84d4a98f97e0f1c6/transformed/classes/classes.dex, /Users/luca/Documents/wymy/v1.1.55/wymy-native-test-3/wymy-native-new-2/wymy-no-expo-splashscreen/node_modules/react-native-svg/android/build/.transforms/8ab24842468869e5816593076e7e99ca/transformed/classes/classes.dex

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 43s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081 -PreactNativeDebugArchitectures=x86 -PreactNativeArchitectures=x86
CMake Deprecation Warning at CMakeLists.txt:42 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


ERROR:/Users/luca/Documents/wymy/v1.1.55/wymy-native-test-3/wymy-native-new-2/wymy-no-expo-splashscreen/node_modules/react-native-gesture-handler/android/build/.transforms/a7b112a41403fb3e84d4a98f97e0f1c6/transformed/classes/classes.dex: D8: Type com.facebook.react.viewmanagers.RNSVGCircleManagerDelegate is defined multiple times: /Users/luca/Documents/wymy/v1.1.55/wymy-native-test-3/wymy-native-new-2/wymy-no-expo-splashscreen/node_modules/react-native-gesture-handler/android/build/.transforms/a7b112a41403fb3e84d4a98f97e0f1c6/transformed/classes/classes.dex, /Users/luca/Documents/wymy/v1.1.55/wymy-native-test-3/wymy-native-new-2/wymy-no-expo-splashscreen/node_modules/react-native-svg/android/build/.transforms/8ab24842468869e5816593076e7e99ca/transformed/classes/classes.dex
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Type com.facebook.react.viewmanagers.RNSVGCircleManagerDelegate is defined multiple times: /Users/luca/Documents/wymy/v1.1.55/wymy-native-test-3/wymy-native-new-2/wymy-no-expo-splashscreen/node_modules/react-native-gesture-handler/android/build/.transforms/a7b112a41403fb3e84d4a98f97e0f1c6/transformed/classes/classes.dex, /Users/luca/Documents/wymy/v1.1.55/wymy-native-test-3/wymy-native-new-2/wymy-no-expo-splashscreen/node_modules/react-native-svg/android/build/.transforms/8ab24842468869e5816593076e7e99ca/transformed/classes/classes.dex
	at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:151)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:138)
	at com.android.build.gradle.internal.tasks.DexMergingWorkAction.merge(DexMergingTask.kt:859)
	at com.android.build.gradle.internal.tasks.DexMergingWorkAction.run(DexMergingTask.kt:805)
	at com.android.build.gradle.internal.profile.ProfileAwareWorkAction.execute(ProfileAwareWorkAction.kt:74)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:66)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:62)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:62)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:59)
	at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:206)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:214)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: /Users/luca/Documents/wymy/v1.1.55/wymy-native-test-3/wymy-native-new-2/wymy-no-expo-splashscreen/node_modules/react-native-gesture-handler/android/build/.transforms/a7b112a41403fb3e84d4a98f97e0f1c6/transformed/classes/classes.dex
	at Version.fakeStackEntry(Version_3.1.51.java:0)
	at com.android.tools.r8.internal.oO0.a(SourceFile:68)
	at com.android.tools.r8.internal.oO0.a(SourceFile:28)
	at com.android.tools.r8.internal.oO0.a(SourceFile:27)
	at com.android.tools.r8.internal.oO0.b(SourceFile:3)
	at com.android.tools.r8.D8.run(D8.java:11)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:136)
	... 33 more
Caused by: com.android.tools.r8.internal.b: Type com.facebook.react.viewmanagers.RNSVGCircleManagerDelegate is defined multiple times: /Users/luca/Documents/wymy/v1.1.55/wymy-native-test-3/wymy-native-new-2/wymy-no-expo-splashscreen/node_modules/react-native-gesture-handler/android/build/.transforms/a7b112a41403fb3e84d4a98f97e0f1c6/transformed/classes/classes.dex, /Users/luca/Documents/wymy/v1.1.55/wymy-native-test-3/wymy-native-new-2/wymy-no-expo-splashscreen/node_modules/react-native-svg/android/build/.transforms/8ab24842468869e5816593076e7e99ca/transformed/classes/classes.dex
	at com.android.tools.r8.internal.il1.a(SourceFile:14)
	at com.android.tools.r8.internal.il1.a(SourceFile:22)
	at com.android.tools.r8.internal.lf1.b(SourceFile:6)
	at com.android.tools.r8.internal.lf1.a(SourceFile:23)
	at com.android.tools.r8.internal.lf1.a(SourceFile:10)
	at java.base/java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:2048)
	at com.android.tools.r8.internal.lf1.a(SourceFile:6)
	at com.android.tools.r8.graph.r2$a.f(SourceFile:4)
	at com.android.tools.r8.dex.b.a(SourceFile:96)
	at com.android.tools.r8.dex.b.a(SourceFile:21)
	at com.android.tools.r8.D8.a(D8.java:21)
	at com.android.tools.r8.D8.d(D8.java:11)
	at com.android.tools.r8.D8.b(D8.java:1)
	at com.android.tools.r8.internal.oO0.a(SourceFile:24)
	... 36 more


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeLibDexDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingTaskDelegate
   > There was a failure while executing work items
      > A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingWorkAction
         > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
           Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
           Type com.facebook.react.viewmanagers.RNSVGCircleManagerDelegate is defined multiple times: /Users/luca/Documents/wymy/v1.1.55/wymy-native-test-3/wymy-native-new-2/wymy-no-expo-splashscreen/node_modules/react-native-gesture-handler/android/build/.transforms/a7b112a41403fb3e84d4a98f97e0f1c6/transformed/classes/classes.dex, /Users/luca/Documents/wymy/v1.1.55/wymy-native-test-3/wymy-native-new-2/wymy-no-expo-splashscreen/node_modules/react-native-svg/android/build/.transforms/8ab24842468869e5816593076e7e99ca/transformed/classes/classes.dex

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 43s

    at makeError (/Users/luca/Documents/wymy/v1.1.55/wymy-native-test-3/wymy-native-new-2/wymy-no-expo-splashscreen/node_modules/execa/index.js:174:9)
    at /Users/luca/Documents/wymy/v1.1.55/wymy-native-test-3/wymy-native-new-2/wymy-no-expo-splashscreen/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/luca/Documents/wymy/v1.1.55/wymy-native-test-3/wymy-native-new-2/wymy-no-expo-splashscreen/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Users/luca/Documents/wymy/v1.1.55/wymy-native-test-3/wymy-native-new-2/wymy-no-expo-splashscreen/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.
```

### Steps to reproduce

1. Build an expo project react native v0.69.7
2. Eject from expo
3. Remove expo completely
4. Enable new architcture
5. Build with `react-native run-android`
6. Build failuer

### Snack or a link to a repository

NA

### Gesture Handler version

2.8.0

### React Native version

0.69.7

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Android emulator

### Device model

Pixel 4 API 30

### Acknowledgements

Yes

**Comment by j-piasecki** [comment]
You mentioned trying other versions of Gesture Handler, was `2.5.0` among them? Since the new architecture isn't really stable at this point we're not actively trying to achieve backward compatibility in this case, so in most cases, a specific version of GH will only work on one version of React Native when using the new arch.

Other than that, have you tried removing Gesture Handler from your app to check if it builds without it? The error you're getting is really baffling as it looks like the SVG classes are also generated in the GH directory.

**Comment by LucaDotti** [comment]
Hello thank you for your reply! Mh dont actually remember I have to re try this with `2.5.0`. 
Regarding removing GH, I did not try it, but I tried to remove `react-native-svg` and the same issue appears. In this case, the duplicate classes are among GH and `react-native` core (of course in this case is a different class).
