### ISSUE TITLE
App build is crashing on android

### ISSUE THREAD

**Issue by YanAnderson-bit** [software-mansion/react-native-gesture-handler#2476]
### Description

My android build is crashing when i click to open the app ( it does not even open ), and the error said that i was using a version of `react-native-gesture-handler` which RNGEstureHandler is deprecated. So i went to the guide that says how to move away from this https://docs.swmansion.com/react-native-gesture-handler/docs/troubleshooting#reporting-issues

I deleted this piece of code from `MainActivity.java` 
```
@Override
    protected ReactActivityDelegate createReactActivityDelegate() {
        return new ReactActivityDelegateWrapper(this, new ReactActivityDelegate(this, getMainComponentName()) {
            @Override
            protected ReactRootView createRootView() {
                return new RNGestureHandlerEnabledRootView(MainActivity.this);
            }
        });
    }
```

just like the guide said.

But im getting another error when i click to open the app

```
java.lang.AssertionError: APK bundle must contain the expected embedded asset index.android.bundle
	at expo.modules.updates.loader.EmbeddedLoader.loadAsset(EmbeddedLoader.kt:85)
	at expo.modules.updates.loader.Loader.downloadAllAssets(Loader.kt:233)
	at expo.modules.updates.loader.Loader.processUpdateManifest(Loader.kt:196)
	at expo.modules.updates.loader.Loader.access$processUpdateManifest(Loader.kt:25)
	at expo.modules.updates.loader.Loader$start$1.onSuccess(Loader.kt:108)
	at expo.modules.updates.loader.EmbeddedLoader.loadManifest(EmbeddedLoader.kt:58)
	at expo.modules.updates.loader.Loader.start(Loader.kt:98)
	at expo.modules.updates.loader.LoaderTask.launchFallbackUpdateFromDisk(LoaderTask.kt:261)
	at expo.modules.updates.loader.LoaderTask.start(LoaderTask.kt:118)
	at expo.modules.updates.UpdatesController.start(UpdatesController.kt:331)
	at expo.modules.updates.UpdatesController$Companion.initialize(UpdatesController.kt:506)
	at expo.modules.updates.UpdatesPackage$createReactNativeHostHandlers$handler$1.onWillCreateReactInstanceManager(UpdatesPackage.kt:46)
	at expo.modules.ReactNativeHostWrapperBase.createReactInstanceManager(ReactNativeHostWrapperBase.kt:27)
	at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:42)
	at com.tsunade.MainApplication.onCreate(MainApplication.java:63)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7096)
	at android.app.ActivityThread.access$1700(ActivityThread.java:277)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2170)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8282)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1074)
```

I dont know what to do anymore

My `eas.js`
```
{
  "cli": {
    "version": ">= 0.35.0"
  },
  "build": {
    "development": {
      "distribution": "internal",
      "android": {
        "gradleCommand": ":app:assembleDebug"
      },
      "ios": {
        "simulator": true
      }
    },
    "preview": {
      "distribution": "internal",
      "android": {
        "buildType": "apk",
        "gradleCommand": ":app:assembleRelease",
        "developmentClient": true
      }
    },
 ```
 
 

### Steps to reproduce

 1. Build the app using command `eas build -p android --profile preview`
 2. Install build and run the app (but it crashes)

### Snack or a link to a repository

.

### Gesture Handler version

2.8.0

### React Native version

0.70.5

### Platforms

Android

### JavaScript runtime

None

### Workflow

Expo bare workflow

### Architecture

None

### Build type

Release mode

### Device

Real device

### Device model

Xiaomi Redmi note 11S

### Acknowledgements

Yes

**Comment by hitaloss** [comment]
same issue here, tried a lot to solve the problem as well...

**Comment by YanAnderson-bit** [comment]
@hitaloss  i solved the problem finally. I got this problem from incorrect expo updates. I tought my app was `managed` type, and it is `bare`. But Still, when i was using `react-dev-tools` to check the changes to manually apply, i was seeing major differences in the files.


My solution was to create another `bare` react native app with the desired sdk version ( 46 in my case ), and then i simple copied `ios,android` folders to my project. Off course, i had to rename some stuff to use my projects name, because  some iOS and android files will have pieces of code with the name that the created app has. So just rename.

After that, i had a fully `ios` and `android` updated folders to sdk version 46, and the build is working like a charm

**Comment by AzadMohammadi-z** [comment]
Hey
I still have this problem, when the app is installed, the app crashes, please help

**Comment by AzadMohammadi-z** [comment]
I still have this problem, when the app is installed, the app crashed, please help

**Comment by VictorioMolina** [comment]
Same here

**Comment by sadewole** [comment]
I'm having this same issue. I have tried everything I found on the internet but none worked.
