### ISSUE TITLE
source-map-generator.js, `throw new Error('Invalid mapping: ' + JSON.stringify({` on createHandler.tsx

### ISSUE THREAD

**Issue by Samykills** [software-mansion/react-native-gesture-handler#2552]
### Description

When building the `release` flavour on android, i always get this error :

`
node_modules/metro-source-map/node_modules/source-map/lib/source-map-generator.js:289
      throw new Error('Invalid mapping: ' + JSON.stringify({
      ^

Error: Invalid mapping: {"generated":{"line":1,"column":801762},"source":"/Users/xuser/Desktop/xc/myapp/node_modules/react-native-gesture-handler/src/handlers/createHandler.tsx","original":{"line":153,"column":-1},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (/Users/xuser/Desktop/xc/myapp/node_modules/metro-source-map/node_modules/source-map/lib/source-map-generator.js:289:13)
    at SourceMapGenerator_addMapping [as addMapping] (/Users/xuser/Desktop/xc/myapp/node_modules/metro-source-map/node_modules/source-map/lib/source-map-generator.js:101:12)
    at /Users/xuser/Desktop/xc/myapp/node_modules/metro-source-map/src/composeSourceMaps.js:42:15
    at MappingsConsumer.eachMapping (/Users/xuser/Desktop/xc/myapp/node_modules/metro-source-map/src/Consumer/AbstractConsumer.js:37:16)
    at composeSourceMaps (/Users/xuser/Desktop/xc/myapp/node_modules/metro-source-map/src/composeSourceMaps.js:36:16)
    at Object.<anonymous> (/Users/xuser/Desktop/xc/myapp/node_modules/react-native/scripts/compose-source-maps.js:56:42)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
`

### Steps to reproduce

version : 2.8.0 - 2.12.0

tried to use the latest version but still get the same,

my apps details:

react-native : 0.67.5
typescript : 4.5.5

### Snack or a link to a repository

na

### Gesture Handler version

2.8.0

### React Native version

0.67.5

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by m-bert** [comment]
Hi @Samykills! Could you provide reproduction that we can look at? I've just build app in release mode and it works fine, there was no `Invalid mapping` error.

Also we would appreciate if you could provide us with your `metro-source-map` version and output of `npx react-native info`.

**Comment by m-bert** [comment]
If you find out that you still see this issue, feel free to reopen it (with proper reproduction).
