### ISSUE TITLE
buildSettings.LIBRARY_SEARCH_PATHS.push is not a function

### ISSUE THREAD

**Issue by achmadk** [software-mansion/react-native-gesture-handler#341]
- [x] Review the documentation: https://kmagiera.github.io/react-native-gesture-handler/
  - [x] Search for existing issues: https://github.com/kmagiera/react-native-gesture-handler/issues
  - [x] Use the latest React Native Gesture Handler release: https://github.com/kmagiera/react-native-gesture-handler/releases

## Environment
React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i3-2310M CPU @ 2.10GHz
      Memory: 1.51 GB / 7.91 GB
    Binaries:
      Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338

## Description
I want to link react-native-gesture-handler to my existing react-native project. Unfortunately I got this error

```sh
rnpm-install info Linking react-native-gesture-handler ios dependency
rnpm-install ERR! Something went wrong while linking. Error: buildSettings.LIBRARY_SEARCH_PATHS.push is not a function
Please file an issue here: https://github.com/facebook/react-native/issues

buildSettings.LIBRARY_SEARCH_PATHS.push is not a function

TypeError: buildSettings.LIBRARY_SEARCH_PATHS.push is not a function
    at pbxProject.addToLibrarySearchPaths (${RN_PROJECT_DIRECTORY}\node_modules\xcode\lib\pbxProject.js:1237:51)
    at pbxProject.addStaticLibrary (${RN_PROJECT_DIRECTORY}\node_modules\xcode\lib\pbxProject.js:467:10)
    at getTargets.forEach.product (${RN_PROJECT_DIRECTORY}\node_modules\react-native\local-cli\link\ios\registerNativeModule.js:61:19)
    at Array.forEach (<anonymous>)
    at registerNativeModuleIOS (${RN_PROJECT_DIRECTORY}\node_modules\react-native\local-cli\link\ios\registerNativeModule.js:56:33)
    at Object.registerNativeModule [as register] (${RN_PROJECT_DIRECTORY}\node_modules\react-native\local-cli\link\ios\common\registerNativeModule.js:15:5)
    at Object.keys.forEach.platform (${RN_PROJECT_DIRECTORY}\node_modules\react-native\local-cli\link\link.js:74:16)
    at Array.forEach (<anonymous>)
    at linkDependency (${RN_PROJECT_DIRECTORY}\node_modules\react-native\local-cli\link\link.js:44:32)
```

## Reproducible Demo
`react-native link react-native-gesture-handler`

**Comment by jakub-gonet** [comment]
This issue is outdated and not really actionable, so I'm closing it.

If you need further help please reply.
