### ISSUE TITLE
Android: react-native link throw error

### ISSUE THREAD

**Issue by canh-tran-niteco** [software-mansion/react-native-gesture-handler#471]
Hi everyone,

I am using:
"react": "16.6.1",
"react-native": "0.57.7",

The error throws when run: react-native link react-native-gesture-handler
```
$ react-native link react-native-gesture-handler
rnpm-install info Linking react-native-gesture-handler ios dependency 
rnpm-install ERR! Something went wrong while linking. Error: Cannot read property 'match' of undefined 
Please file an issue here: https://github.com/facebook/react-native/issues 

Cannot read property 'match' of undefined

TypeError: Cannot read property 'match' of undefined
    at findLineToAddPod (/home/canhtran/Projects/MobileApp/react-native-pzy/node_modules/react-native/local-cli/link/pods/findLineToAddPod.js:22:17)
    at getLinesToAddEntry (/home/canhtran/Projects/MobileApp/react-native-pzy/node_modules/react-native/local-cli/link/pods/registerNativeModule.js:36:12)
    at registerNativeModulePods (/home/canhtran/Projects/MobileApp/react-native-pzy/node_modules/react-native/local-cli/link/pods/registerNativeModule.js:25:27)
    at Object.registerNativeModule [as register] (/home/canhtran/Projects/MobileApp/react-native-pzy/node_modules/react-native/local-cli/link/ios/common/registerNativeModule.js:13:5)
    at Object.keys.forEach.platform (/home/canhtran/Projects/MobileApp/react-native-pzy/node_modules/react-native/local-cli/link/link.js:74:16)
    at Array.forEach (<anonymous>)
    at linkDependency (/home/canhtran/Projects/MobileApp/react-native-pzy/node_modules/react-native/local-cli/link/link.js:44:32)
    at <anonymous>
```

**Comment by jacquesdev** [comment]
I had to go back to version https://github.com/kmagiera/react-native-gesture-handler/releases/tag/1.0.10, then I could link, and then upgrade to the latest after

**Comment by jakub-gonet** [comment]
Hi!
I believe this issue is solved, so I'm closing it.
If you still face this problem don't hesitate to ask.
