### ISSUE TITLE
[Bug] Failed to run-android with error:com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: Unknown failure: Segmentation fault

### ISSUE THREAD

**Issue by zxccvvv** [software-mansion/react-native-gesture-handler#758]
I don't know if this is a right place to report an issue, I've tried to run React-Native android but i got an error:

>error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
Note: D:\Project\BSS (Mobile Agency)\MAS\MobileAgency\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerButtonViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Unable to install D:\Project\BSS (Mobile Agency)\MAS\MobileAgency\android\app\build\outputs\apk\debug\app-debug.apk
com.android.ddmlib.InstallException: Unknown failure: Segmentation fault

there's another log that caused by `react-native-community` CLI

>BUILD FAILED in 1m 37s
    at checkExecSyncError (child_process.js:629:11)
    at execFileSync (child_process.js:647:13)
    at runOnAllDevices (d:\Project\BSS (Mobile Agency)\MAS\MobileAgency\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:74:39)
    at buildAndRun (d:\Project\BSS (Mobile Agency)\MAS\MobileAgency\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:158:41)
    at Object.runAndroid [as func] (d:\Project\BSS (Mobile Agency)\MAS\MobileAgency\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:106:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by baselbj** [comment]
same issue here did you solve it?

**Comment by jakub-gonet** [comment]
This isn't directly related to RNGH, it's an installation issue.

**Comment by ibalaji777** [comment]
same issue facing any one know solution
